version: '3'
services:
  mariadb:
    container_name: test_mariadb
    image: mariadb:10.4.11_withBackup
    build: mariadb
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    command: --character-set-server=utf8
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=test_mariadb
      - MYSQL_USER=test
      - MYSQL_PASSWORD=1qaz2wsx
      
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    hostname: mysql-exporter
    restart: always
    command: --config.my-cnf=/cfg/.my.cnf
    volumes:
      - ./mysql-exporter/.my.cnf:/cfg/.my.cnf:ro
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: 'exporter:123456@(mariadb:3306)'