version: '2'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    user: "0:0"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "prometheus-ip:${PROMETHEUS_HOST}"
      - "mysql-ip:${MYSQL_HOST}"
      - "redis-ip:${REDIS_HOST}"
    networks:
      - monitor

  alertmanager:  #预警模块
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    ports:
      - "9093:9093"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    # ports:
    #   - "9100:9100"
    networks:
      - monitor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    # ports:
    #   - "8899:8080"
    networks:
      - monitor

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    hostname: redis-exporter
    restart: always
    # ports:
    #   - "9121:9121"
    command: --redis.addr=redis://${REDIS_HOST}:6379

  mysql-exporter-db1:
    image: prom/mysqld-exporter
    container_name: mysql-exporter-db1
    hostname: mysql-exporter-db1
    restart: always
    command: --config.my-cnf=/cfg/.my.cnf
    volumes:
      - ./mysql-exporter/.my.cnf:/cfg/.my.cnf:ro
    # ports:
    #   - "9104:9104"
    environment:
      DATA_SOURCE_NAME: 'exporter:123456@(${MYSQL_HOST}:3306)'